/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Division = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'weightClass' : IDL.Text,
});
export const Competitor = IDL.Record({
  'id' : IDL.Nat,
  'dojo' : IDL.Text,
  'name' : IDL.Text,
  'weightClass' : IDL.Text,
  'beltRank' : IDL.Text,
  'divisionId' : IDL.Nat,
});
export const Bout = IDL.Record({
  'id' : IDL.Nat,
  'winnerId' : IDL.Opt(IDL.Nat),
  'competitor1Id' : IDL.Nat,
  'competitor2Id' : IDL.Opt(IDL.Nat),
  'divisionId' : IDL.Nat,
  'boutNumber' : IDL.Nat,
  'round' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCompetitor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createDivision' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteDivision' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'generateBracket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getDivisionWithBouts' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'division' : Division,
            'competitors' : IDL.Vec(Competitor),
            'bouts' : IDL.Vec(Bout),
          })
        ),
      ],
      ['query'],
    ),
  'listCompetitorsByDivision' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Competitor)],
      ['query'],
    ),
  'listDivisions' : IDL.Func([], [IDL.Vec(Division)], ['query']),
  'recordResult' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'removeCompetitor' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'resetBracket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'seedSampleData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Division = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'weightClass' : IDL.Text,
  });
  const Competitor = IDL.Record({
    'id' : IDL.Nat,
    'dojo' : IDL.Text,
    'name' : IDL.Text,
    'weightClass' : IDL.Text,
    'beltRank' : IDL.Text,
    'divisionId' : IDL.Nat,
  });
  const Bout = IDL.Record({
    'id' : IDL.Nat,
    'winnerId' : IDL.Opt(IDL.Nat),
    'competitor1Id' : IDL.Nat,
    'competitor2Id' : IDL.Opt(IDL.Nat),
    'divisionId' : IDL.Nat,
    'boutNumber' : IDL.Nat,
    'round' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCompetitor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createDivision' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteDivision' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'generateBracket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getDivisionWithBouts' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'division' : Division,
              'competitors' : IDL.Vec(Competitor),
              'bouts' : IDL.Vec(Bout),
            })
          ),
        ],
        ['query'],
      ),
    'listCompetitorsByDivision' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Competitor)],
        ['query'],
      ),
    'listDivisions' : IDL.Func([], [IDL.Vec(Division)], ['query']),
    'recordResult' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'removeCompetitor' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'resetBracket' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'seedSampleData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };