/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Competitor {
    id: bigint;
    dojo: string;
    name: string;
    weightClass: string;
    beltRank: string;
    divisionId: bigint;
}
export interface Division {
    id: bigint;
    name: string;
    weightClass: string;
}
export interface Bout {
    id: bigint;
    winnerId?: bigint;
    competitor1Id: bigint;
    competitor2Id?: bigint;
    divisionId: bigint;
    boutNumber: bigint;
    round: bigint;
}
export interface backendInterface {
    addCompetitor(name: string, dojo: string, beltRank: string, weightClass: string, divisionId: bigint): Promise<bigint>;
    createDivision(name: string, weightClass: string): Promise<bigint>;
    deleteDivision(id: bigint): Promise<boolean>;
    generateBracket(divisionId: bigint): Promise<boolean>;
    getDivisionWithBouts(divisionId: bigint): Promise<{
        division: Division;
        competitors: Array<Competitor>;
        bouts: Array<Bout>;
    } | null>;
    listCompetitorsByDivision(divisionId: bigint): Promise<Array<Competitor>>;
    listDivisions(): Promise<Array<Division>>;
    recordResult(boutId: bigint, winnerId: bigint): Promise<boolean>;
    removeCompetitor(id: bigint): Promise<boolean>;
    resetBracket(divisionId: bigint): Promise<boolean>;
    /**
     * / From the old backend that will not even compile with the new Map library:
     */
    seedSampleData(): Promise<void>;
}
import type { Bout as _Bout, Competitor as _Competitor, Division as _Division } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCompetitor(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCompetitor(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCompetitor(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createDivision(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDivision(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDivision(arg0, arg1);
            return result;
        }
    }
    async deleteDivision(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDivision(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDivision(arg0);
            return result;
        }
    }
    async generateBracket(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.generateBracket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateBracket(arg0);
            return result;
        }
    }
    async getDivisionWithBouts(arg0: bigint): Promise<{
        division: Division;
        competitors: Array<Competitor>;
        bouts: Array<Bout>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDivisionWithBouts(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDivisionWithBouts(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCompetitorsByDivision(arg0: bigint): Promise<Array<Competitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCompetitorsByDivision(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCompetitorsByDivision(arg0);
            return result;
        }
    }
    async listDivisions(): Promise<Array<Division>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDivisions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDivisions();
            return result;
        }
    }
    async recordResult(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.recordResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordResult(arg0, arg1);
            return result;
        }
    }
    async removeCompetitor(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCompetitor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCompetitor(arg0);
            return result;
        }
    }
    async resetBracket(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetBracket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetBracket(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
}
function from_candid_Bout_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bout): Bout {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        division: _Division;
        competitors: Array<_Competitor>;
        bouts: Array<_Bout>;
    }]): {
    division: Division;
    competitors: Array<Competitor>;
    bouts: Array<Bout>;
} | null {
    return value.length === 0 ? null : from_candid_record_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    division: _Division;
    competitors: Array<_Competitor>;
    bouts: Array<_Bout>;
}): {
    division: Division;
    competitors: Array<Competitor>;
    bouts: Array<Bout>;
} {
    return {
        division: value.division,
        competitors: value.competitors,
        bouts: from_candid_vec_n3(_uploadFile, _downloadFile, value.bouts)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    winnerId: [] | [bigint];
    competitor1Id: bigint;
    competitor2Id: [] | [bigint];
    divisionId: bigint;
    boutNumber: bigint;
    round: bigint;
}): {
    id: bigint;
    winnerId?: bigint;
    competitor1Id: bigint;
    competitor2Id?: bigint;
    divisionId: bigint;
    boutNumber: bigint;
    round: bigint;
} {
    return {
        id: value.id,
        winnerId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.winnerId)),
        competitor1Id: value.competitor1Id,
        competitor2Id: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.competitor2Id)),
        divisionId: value.divisionId,
        boutNumber: value.boutNumber,
        round: value.round
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bout>): Array<Bout> {
    return value.map((x)=>from_candid_Bout_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
